#!/usr/bin/env python3
from pathlib import Path
import subprocess, sys, json, tempfile, shutil, os, hashlib
ROOT=Path(__file__).resolve().parents[1]
PY=sys.executable
sys.dont_write_bytecode=True
os.environ["PYTHONDONTWRITEBYTECODE"]="1"
REPORTS=ROOT/'test-reports'; REPORTS.mkdir(exist_ok=True)
def run(cmd):
    proc=subprocess.run(cmd, cwd=str(ROOT), text=True, capture_output=True)
    try: payload=json.loads(proc.stdout.strip().splitlines()[-1]) if proc.stdout.strip() else {}
    except Exception: payload={}
    return {'command':' '.join(map(str,cmd)),'exit_code':proc.returncode,'stdout':proc.stdout,'stderr':proc.stderr,'payload':payload}
def fixture_cmds(name):
    f=ROOT/'fixtures'/name; r=REPORTS/name; r.mkdir(parents=True, exist_ok=True)
    return [
      [PY,'validators/validate_schema.py','--schema','schemas/hybrid-script.schema.json','--instance',str(f/'script.json'),'--report',str(r/'schema-script.json')],
      [PY,'validators/validate_schema.py','--schema','schemas/core-story-beats.schema.json','--instance',str(f/'core-story-beats.json'),'--report',str(r/'schema-core-story-beats.json')],
      [PY,'validators/validate_schema.py','--schema','schemas/core-story-beat-coverage.schema.json','--instance',str(f/'coverage-report.json'),'--report',str(r/'schema-coverage.json')],
      [PY,'validators/validate_core_story_beats.py','--beat-registry',str(f/'core-story-beats.json'),'--report',str(r/'core-story-beats.json')],
      [PY,'validators/validate_coverage_evidence.py','--script',str(f/'script.md'),'--script-json',str(f/'script.json'),'--beat-registry',str(f/'core-story-beats.json'),'--coverage-report',str(f/'coverage-report.json'),'--report',str(r/'coverage-evidence.json')],
      [PY,'validators/validate_markdown_json_equivalence.py','--script',str(f/'script.md'),'--script-json',str(f/'script.json'),'--coverage-report',str(f/'coverage-report.json'),'--report',str(r/'equivalence.json')],
      [PY,'validators/validate_handoff_contract.py','--handoff',str(f/'script-handoff-manifest.json'),'--base-dir',str(f),'--report',str(r/'handoff.json')],
      [PY,'validators/validate_artifact_integrity.py','--artifact-registry',str(f/'artifact-registry.json'),'--evidence-sidecar',str(f/'evidence-sidecar.json'),'--review-request',str(f/'script-approval-request.json'),'--base-dir',str(f),'--report',str(r/'integrity.json')],
      [PY,'validators/validate_assumptions_and_extensions.py','--script',str(f/'script.md'),'--production-assumptions',str(f/'production-assumption-log.json'),'--source-conflicts',str(f/'source-conflict-registry.json'),'--adaptation-extension-registry',str(f/'adaptation-extension-registry.json'),'--report',str(r/'assumptions.json')],
      [PY,'validators/validate_source_claim_audit.py','--source-claim-audit',str(f/'source-claim-audit.json'),'--source-conflicts',str(f/'source-conflict-registry.json'),'--report',str(r/'source-claim-audit.json')],
      [PY,'validators/validate_creator_presentation.py','--presentation',str(f/'presentation.md'),'--script',str(f/'script.md'),'--report',str(r/'presentation.json')]
    ]
results=[]
for fixture in ['pilot-shengsi','neutral-project','conflict-free-project']:
    for cmd in fixture_cmds(fixture): results.append(run(cmd))
results.append(run([PY,'validators/validate_genericity.py','--root',str(ROOT),'--forbidden-terms','tests/forbidden-terms.txt','--report',str(REPORTS/'genericity.json')]))
mut=run([PY,'tests/run_mutation_tests.py']); results.append(mut)
adv=run([PY,'tests/run_adversarial_tests.py']); results.append(adv)
phase_b=run([PY,'tests/run_phase_b_contract_tests.py']); results.append(phase_b)
# Validators import shared modules during this run; remove generated bytecode
# before the package-content scan so the test verifies distributable files.
for p in ROOT.rglob('__pycache__'):
    shutil.rmtree(p, ignore_errors=True)
for p in list(ROOT.rglob('*.pyc')) + list(ROOT.rglob('*.pyo')):
    try:
        p.unlink()
    except FileNotFoundError:
        pass
# dependency content scan outside fixtures/vendor/test-reports
scan_files=[]
for p in ROOT.rglob('*'):
    if not p.is_file(): continue
    rel=str(p.relative_to(ROOT))
    if rel.startswith(('fixtures/','vendor/','test-reports/','.deps/')) or rel.endswith('forbidden-terms.txt') or '__pycache__' in rel: continue
    if p.suffix in ['.md','.json','.py','.txt','.yaml','.yml']:
        scan_files.append(p)
absolute=0; parent=0; project=0; cache_files=0; platform_binaries=0
abs_marker='/'+'Users/'
parent_terms=['phase'+'-a/','phase'+'-b/','phase'+'-c/','ai'+'-drama'+'-script'+'-quality'+'-lab']
project_terms=['AI'+'-man'+'-shengsi','shengsi'+'-chapter','FIXED'+'_SAMPLE'+'_BEAT'+'_ID']
for p in scan_files:
    text=p.read_text(encoding='utf-8', errors='ignore')
    absolute += text.count(abs_marker)
    parent += sum(text.count(t) for t in parent_terms)
    project += sum(text.count(t) for t in project_terms)
for p in ROOT.rglob('*'):
    rel=str(p.relative_to(ROOT))
    if rel.startswith('.deps/'):
        continue
    if '__pycache__' in rel or p.name in ['.DS_Store'] or p.suffix in ['.pyc','.pyo']:
        cache_files += 1
    if p.suffix == '.so':
        platform_binaries += 1
all_pass=all(r['exit_code']==0 for r in results) and absolute==0 and parent==0 and project==0 and cache_files==0 and platform_binaries==0
report={'final_status':'pass' if all_pass else 'fail','absolute_path_dependency_count':absolute,'parent_phase_dependency_count':parent,'project_specific_hardcode_count':project,'package_cache_file_count':cache_files,'platform_binary_count':platform_binaries,'results':results}
(REPORTS/'run-all-tests.json').write_text(json.dumps(report, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
print(json.dumps(report, ensure_ascii=False))
sys.exit(0 if all_pass else 1)
